[package]
name = "learning-rust"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace]
members = [ "nixsilvam/restaurant",
    "nixsilvam/rustbook"
, "nixsilvam/top_interview_questions_easy"]
